name: Compile Mac Wallpaper

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15-intel

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile
        run: |
          clang++ main.mm \
            -framework Cocoa \
            -framework WebKit \
            -arch x86_64 \
            -mmacosx-version-min=10.13 \
            -o HTMLWallpaper

      - name: Prepare Test App
        run: |
          mkdir -p Wallpaper-App
          cp HTMLWallpaper Wallpaper-App/
          cp Test.html Wallpaper-App/

      - name: Verify Files
        run: |
          ls -lh Wallpaper-App

      - name: Package
        run: |
          cd Wallpaper-App
          zip -r ../Wallpaper-App.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Wallpaper-App-Test
          path: Wallpaper-App.zip
